[project]
name = "mdd-heterogeneity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bed-reader>=1.0.6",
    "enformer-pytorch>=0.8.11",
    "fastapy>=1.0.5",
    "numpy>=2.3.5",
    "pysam>=0.23.3",
    "scanpy>=1.11.5",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "wandb>=0.23.1",
]
