from __future__ import annotations
import argparse
import logging
import pandas as pd
from pathlib import Path
import fastapy
import subprocess

"""
get_obs_vars.py

Script that takes input from the CSV generated by get_target_vars.py, extracts
the ENSEMBL gene IDs, and maps them to TSS locations using the GTF & FASTA files
from a reference genome (e.g. hg38). To locate the TSS, the script uses
get_gene_tss.sh. This gives us the start and end location of each gene in the
reference genome, which we can then use to extract the window around the TSS for
downstream analysis.

https://ftp.ensembl.org/pub/release-115/gtf/homo_sapiens/
https://ftp.ensembl.org/pub/release-115/fasta/homo_sapiens/dna/
"""

def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Prepare target variables for downstream analysis."
    )
    parser.add_argument(
        "-i-csv", "--input-csv",
        type=Path,
        required=True,
        help="Path to input file generated by get_target_vars.py (*.csv)."
    )
    parser.add_argument(
        "-i-gtf", "--input-gtf",
        type=Path,
        required=True,
        help="Path to input GTF file from reference genome."
    )
    parser.add_argument(
        "-i-fasta", "--input-fasta",
        type=Path,
        required=True,
        help="Path to input FASTA file from reference genome."
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        required=True,
        help="Path to write output file (*.csv)."
    )
    parser.add_argument(
        "-v", "--verbose",
        action="count",
        default=0,
        help="Increase verbosity."
    )
    return parser.parse_args()

def setup_logging(verbosity: int) -> None:
    """Configure basic logging based on verbosity level."""
    level = logging.INFO
    if verbosity >= 1:
        level = logging.DEBUG
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

def load_data(input_path: Path) -> list[str] | dict[str, fastapy.Sequence]:
    """Load data from `input_path`."""
    logging.info("Loading data from %s", input_path)
    file_type = input_path.suffix
    if (file_type == ".csv"):
        with open(input_path, 'r') as f:
            return f.readline().strip().split(",")[1:] # read only ensembl ids from first line
    elif (file_type == ".fa"):
        return fastapy.to_dict(fastapy.parse(input_path))
    else: # we don't read the gtf file here, is done by bash script
        raise ValueError("Input file must be an .csv or .fa file")

def get_gene_tss(ensids: list[str], gtf_path: Path) -> pd.DataFrame:
    """Get TSS locations for given ENSEMBL IDs using the GTF file."""
    logging.info("Getting TSS locations for %d genes", len(ensids))

    cmd = ["./preprocessing/get_gene_tss.sh", str(gtf_path), *ensids]
    try:
        proc = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError("get_gene_tss.sh failed") from e

    out = proc.stdout.strip()
    if not out:
        raise RuntimeError("get_gene_tss.sh returned no output")

    rows = []
    for line in out.splitlines():
        line = line.strip()
        # try common delimiters (tab, space, comma)
        parts = line.split("\t")
        assert(len(parts) == 4)

        chrom, ens, start, end = parts[0], parts[1], int(parts[2]), int(parts[3])
        rows.append((chrom, ens, start, end))

    logging.info("Retrieved TSS for %d of %d genes", len(rows), len(ensids))

    df = pd.DataFrame(rows, columns=["chrom", "ensid", "tss_start", "tss_end"])
    return df

def get_gene_sequences(tss_df: pd.DataFrame, fasta_dict: dict[str, fastapy.Sequence]) -> pd.DataFrame:

    for _, row in tss_df.iterrows():
        chrom     = row['chrom']
        ensid     = row['ensid']
        tss_start = row['tss_start']
        tss_end   = row['tss_end']

        # get chromosome sequence
        seq = fasta_dict.get(chrom)
        if seq is None:
            logging.warning("Chromosome %s not found in FASTA", chrom)
            continue

        # now we want to exctract the sub-sequence around the TSS
        # idea from seq2cells: if TSS cannot be centered without padding
        # the sequence, shift the window to avoid padding as much as possible
        window_size = tss_end - tss_start
        seq_len = len(seq.seq)
        
        if tss_start < 0:
            actual_start = 0
            actual_end   = min(window_size, seq_len)
        elif tss_end > seq_len:
            actual_end   = seq_len
            actual_start = max(0, seq_len - window_size)
        else:
            actual_start = tss_start
            actual_end   = tss_end
        
        # extract sequence
        gene_seq = seq.seq[actual_start:actual_end]
        # if new end exceeds original end, we pad with Ns
        if len(gene_seq) < window_size:
            padding_needed = window_size - len(gene_seq)
            if actual_start == 0: # pad at beginning
                gene_seq = "N" * padding_needed + gene_seq
            else: # pad at end
                gene_seq = gene_seq + "N" * padding_needed

        assert len(gene_seq) == (tss_end - tss_start), "Sequence length mismatch"

        # save sequence back to dataframe
        tss_df.loc[tss_df['ensid'] == ensid, 'sequence'] = gene_seq

    return tss_df

def save_output(data: pd.DataFrame, output_path: Path) -> None:
    """Save processed data to `output_path`."""
    logging.info("Saving output to %s", output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    data.to_csv(output_path, index=False)

def main() -> None:
    args = parse_args()
    setup_logging(args.verbose)
    logging.debug("Arguments: %s", args)

    ensids = load_data(args.input_csv)
    tss_df = get_gene_tss(ensids, args.input_gtf)
    logging.debug("\n%s", tss_df.head())

    hg38sq = load_data(args.input_fasta)
    seq_df = get_gene_sequences(tss_df, hg38sq)
    logging.debug("\n%s", seq_df.head())

    save_output(seq_df, args.output)

    logging.info("Done.")

if __name__ == "__main__":
    main()