from __future__ import annotations
import argparse
import logging
import pandas as pd
import anndata as ad
from pathlib import Path
import fastapy
import subprocess

"""
get_obs_vars.py

Script that takes a list of ENSEMBL gene IDs and maps them to TSS locations
using the GTF & FASTA files from a reference genome (e.g. hg37). To locate
the TSS, the script uses get_gene_tss.sh. This gives us the start and end
location of each gene in the reference genome, which we can then use to
extract the window around the TSS for downstream analysis.

The gene IDs can be loaded from either:
  - a CSV produced by get_target_vars.py (header row holds the ENSIDs), or
  - an .h5ad file produced by get_ge_per_ind.py (var.index holds the ENSIDs).

https://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/
https://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/
"""

def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Prepare target variables for downstream analysis."
    )
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        "-i-csv", "--input-csv",
        type=Path,
        help="Path to input file generated by get_target_vars.py (*.csv). "
             "The header row's columns (after the first) are read as ENSIDs."
    )
    input_group.add_argument(
        "-i-h5ad", "--input-h5ad",
        type=Path,
        help="Path to pseudo-bulk file generated by get_ge_per_ind.py (*.h5ad). "
             "Gene IDs are read from var.index."
    )
    parser.add_argument(
        "-i-gtf", "--input-gtf",
        type=Path,
        required=True,
        help="Path to input GTF file from reference genome."
    )
    parser.add_argument(
        "-i-fasta", "--input-fasta",
        type=Path,
        required=True,
        help="Path to input FASTA file from reference genome."
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        required=True,
        help="Path to write output file (*.csv)."
    )
    parser.add_argument(
        "-oc", "--only-coding",
        action="store_true",
        help="Only consider protein-coding genes."
    )
    parser.add_argument(
        "-v", "--verbose",
        action="count",
        default=0,
        help="Increase verbosity."
    )
    return parser.parse_args()

def setup_logging(verbosity: int) -> None:
    """Configure basic logging based on verbosity level."""
    level = logging.INFO
    if verbosity >= 1:
        level = logging.DEBUG
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

def load_data(input_path: Path) -> list[str] | dict[str, fastapy.Sequence]:
    """Load data from `input_path`. Dispatches on file extension."""
    logging.info("Loading data from %s", input_path)
    file_type = input_path.suffix
    if file_type == ".csv":
        with open(input_path, 'r') as f:
            return f.readline().strip().split(",")[1:] # read only ensembl ids from first line
    elif file_type == ".h5ad":
        # Open in backed mode so we read just var/obs metadata without
        # pulling the full expression matrix into memory.
        adata = ad.read_h5ad(input_path, backed="r")
        try:
            ensids = adata.var.index.astype(str).tolist()
        finally:
            if adata.isbacked:
                adata.file.close()
        logging.debug("Read %d ENSIDs from %s", len(ensids), input_path)
        return ensids
    elif file_type == ".fa":
        return fastapy.to_dict(fastapy.parse(input_path))
    else: # we don't read the gtf file here, is done by bash script
        raise ValueError("Input file must be a .csv, .h5ad, or .fa file")

def get_gene_tss(ensids: list[str], gtf_path: Path, only_coding: bool) -> pd.DataFrame:
    """Get TSS locations for given ENSEMBL IDs using the GTF file."""
    logging.info("Getting TSS locations for %d genes", len(ensids))

    cmd = ["./src/preprocessing/get_gene_tss.sh", "--protein-coding" if only_coding else "", str(gtf_path), *ensids]
    try:
        proc = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError("get_gene_tss.sh failed") from e

    out = proc.stdout.strip()
    if not out:
        raise RuntimeError("get_gene_tss.sh returned no output")

    rows = []
    for line in out.splitlines():
        line = line.strip()
        # try common delimiters (tab, space, comma)
        parts = line.split("\t")
        assert(len(parts) == 5)

        chrom, ens, tss, start, end = parts[0], parts[1], int(parts[2]), int(parts[3]), int(parts[4])
        rows.append((chrom, ens, tss, start, end))

    logging.info("Retrieved TSS for %d of %d genes", len(rows), len(ensids))

    df = pd.DataFrame(rows, columns=["chrom", "ensid", "tss", "start", "end"])
    return df

def get_gene_sequences(tss_df: pd.DataFrame, fasta_dict: dict[str, fastapy.Sequence]) -> pd.DataFrame:
    kept_rows = []

    for _, row in tss_df.iterrows():
        chrom = row["chrom"]
        ensid = row["ensid"]
        tss   = row["tss"]
        start = row["start"]
        end   = row["end"]

        # get chromosome sequence
        seq = fasta_dict.get(chrom)
        if seq is None:
            logging.warning("Chromosome %s not found in FASTA for %s; dropping row", chrom, ensid)
            continue

        # extract subsequence around the TSS
        window_size = end - start
        seq_len = len(seq.seq)

        if start < 0:
            actual_start = 0
            actual_end   = min(window_size, seq_len)
        elif end > seq_len:
            actual_end   = seq_len
            actual_start = max(0, seq_len - window_size)
        else:
            actual_start = start
            actual_end   = end

        gene_seq = seq.seq[actual_start:actual_end]

        if len(gene_seq) < window_size:
            padding_needed = window_size - len(gene_seq)
            if actual_start == 0:
                gene_seq = "N" * padding_needed + gene_seq
            else:
                gene_seq = gene_seq + "N" * padding_needed

        assert len(gene_seq) == window_size, "Sequence length mismatch"

        kept_rows.append({
            "chrom": chrom,
            "ensid": ensid,
            "tss": tss,
            "start": start,
            "end": end,
            "sequence": gene_seq,
            "actual_start": actual_start,
            "actual_end": actual_end,
        })

    out_df = pd.DataFrame(kept_rows)
    logging.info("Kept %d of %d rows", len(out_df), len(tss_df))
    return out_df

def save_output(data: pd.DataFrame, output_path: Path) -> None:
    """Save processed data to `output_path`."""
    logging.info("Saving output to %s", output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    data.to_csv(output_path, index=False)

def main() -> None:
    args = parse_args()
    setup_logging(args.verbose)
    logging.debug("Arguments: %s", args)

    genes_input = args.input_csv if args.input_csv is not None else args.input_h5ad
    ensids = load_data(genes_input)
    tss_df = get_gene_tss(ensids, args.input_gtf, args.only_coding)
    logging.debug("\n%s", tss_df.head())

    hg38sq = load_data(args.input_fasta)
    seq_df = get_gene_sequences(tss_df, hg38sq)
    logging.debug("\n%s", seq_df.head())

    save_output(seq_df, args.output)

    logging.info("Done.")

if __name__ == "__main__":
    main()